# Image for serving HTTP/PHP environment:
FROM acdh/base_http_php
# Note: use the base_ version to create your own further customized containers!
MAINTAINER Mateusz Żółtak <mateusz.zoltak@oeaw.ac.at>
# this should be added asap: /var/log/apache2
VOLUME /var/www/html
# Optional VOLUME /var/www/exec /var/www/config

