FROM docker.elastic.co/elasticsearch/elasticsearch:7.0.0
MAINTAINER Omar Siam <omar.siam@oeaw.ac.at>

VOLUME /usr/share/elasticsearch/data /usr/share/elasticsearch/logs /usr/share/elasticsearch/config

EXPOSE 9200 9300