FROM docker.elastic.co/elasticsearch/elasticsearch:6.2.2
MAINTAINER Omar Siam <omar.siam@oeaw.ac.at>

VOLUME /usr/share/elasticsearch/data /usr/share/elasticsearch/log /usr/share/elasticsearch/config

EXPOSE 9200 9300