on:
  push:
    branch: [master]
jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build images
        run: |
          docker build --rm -t acdhch/php:8 http_php8
      - name: authorize against docker hub
        uses: docker/login-action@v1
        with:
          username: zozlak
          password: ${{ secrets.DOCKERHUBTOKEN }}
      - name: push to docker hub
        run: |
          docker push acdhch/php:8

