on:
  push:
    branch: [master]
jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: authorize against docker hub
        uses: docker/login-action@v2
        with:
          username: acdhtech
          password: ${{ secrets.DOCKERHUBTOKEN }}
      - name: build php image
        run: |
          docker build --rm --label "buildUrl=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" -t acdhch/php:8.2 http_php8
      - name: push to docker hub php
        run: |
          docker push acdhch/php:8.2
      - name: build noske:5.66.3-2.223.6-open image
        run: |
          docker build --rm --label "buildUrl=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" -t acdhch/noske:5.66.3-2.223.6-open noske_crystal
      - name: push to docker hub noske:5.66.3-2.223.6-open
        run: |
          docker push acdhch/noske:5.66.3-2.223.6-open
      - name: build noske:3.116.13-2.167.8-open-ubuntu image
        run: |
          docker build --rm --label "buildUrl=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" -t acdhch/noske:3.116.13-2.167.8-open-ubuntu noske
          docker tag acdhch/noske:3.116.13-2.167.8-open-ubuntu acdhch/noske:3.116.13-2.167.8-open
      - name: push to docker hub
        run: |
          docker push acdhch/noske:3.116.13-2.167.8-open-ubuntu
          docker push acdhch/noske:3.116.13-2.167.8-open

